/**
 * Canonical JSON serialization for rendered artifacts.
 *
 * Every rendered file goes through here, so two renders of the same registry
 * produce byte-identical files: keys sorted, two-space indent, trailing
 * newline, no timestamps, no host- or run-dependent values.
 *
 * Strict `JSON.stringify` only — no JSONC, no comments, no trailing commas.
 * These files are read by `builtins.fromJSON` in the consuming nix repos and
 * it rejects all three.
 */

export type JsonValue = string | number | boolean | null | JsonValue[] | JsonObject;
export interface JsonObject {
  [key: string]: JsonValue;
}

/**
 * Header stamped into every rendered file (see `stampHeader`). Fixed text —
 * no timestamp, no version — so re-rendering an unchanged registry is a no-op
 * diff.
 */
export const DO_NOT_EDIT =
  "DO NOT EDIT — generated by infra-rules from the registry. Edit the registry and re-render.";

/** The key `stampHeader` writes the header under. Sorts first in any output. */
export const HEADER_KEY = "_generated";

/**
 * Returns `value` with the DO NOT EDIT header attached.
 *
 * The top level of a rendered file must be an object: a bare array has
 * nowhere to carry the header. A renderer needing a list wraps it in a named
 * key, which is also what the nix side reads.
 */
export function stampHeader(value: JsonObject): JsonObject {
  return { ...value, [HEADER_KEY]: DO_NOT_EDIT };
}

/** Depth-first copy with every object's keys in sorted order. */
function sortKeys(value: JsonValue): JsonValue {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value === null || typeof value !== "object") return value;
  const out: JsonObject = {};
  for (const key of Object.keys(value).sort()) {
    const child = value[key];
    if (child === undefined) continue;
    out[key] = sortKeys(child);
  }
  return out;
}

/**
 * Rejects values `JSON.stringify` would silently drop or emit as `null`,
 * which would make an artifact quietly wrong instead of loudly unrenderable.
 */
function assertSerializable(value: unknown, path: string): asserts value is JsonValue {
  if (value === null) return;
  switch (typeof value) {
    case "string":
    case "boolean":
      return;
    case "number":
      if (!Number.isFinite(value)) {
        throw new Error(`canonical: non-finite number at ${path}`);
      }
      return;
    case "object":
      if (Array.isArray(value)) {
        value.forEach((item, i) => assertSerializable(item, `${path}[${i}]`));
        return;
      }
      for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
        if (child === undefined) continue;
        assertSerializable(child, `${path}.${key}`);
      }
      return;
    default:
      throw new Error(`canonical: unserializable ${typeof value} at ${path}`);
  }
}

/** Canonical text for a rendered file: sorted keys, 2-space indent, trailing newline. */
export function canonicalJson(value: JsonObject): string {
  assertSerializable(value, "$");
  return `${JSON.stringify(sortKeys(value), null, 2)}\n`;
}
